-- WeatherLog table --
DROP TABLE WEATHERLOG;
DROP SEQUENCE WEATHERLOG_SEQ;

CREATE SEQUENCE WEATHERLOG_SEQ START WITH 1;

CREATE TABLE WEATHERLOG(
  ID NUMBER(10) DEFAULT WEATHERLOG_SEQ.nextval NOT NULL,
  RESPONSEID VARCHAR2(256) NOT NULL,
  LOCATION VARCHAR2(50) NOT NULL,
  ACTUALWEATHER VARCHAR2(50) NOT NULL,
  TEMPERATURE VARCHAR2(50) NOT NULL,
  DTIMEINSERTED TIMESTAMP NOT NULL
);

ALTER TABLE WEATHERLOG
  ADD(CONSTRAINT WEATHERLOG_PK PRIMARY KEY (ID));
  
ALTER TABLE WEATHERLOG
  ADD CONSTRAINT RESPONSEID_UNIQUE UNIQUE (RESPONSEID) DEFERRABLE NOVALIDATE;
  

SELECT * FROM WEATHERLOG;